development:
  adapter: postgresql
  encoding: unicode
  database: ins-outs_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ins-outs_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ins-outs_production
  pool: 5